name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Configure agent
        run: go run mage.go ConfigureAgent
      - name: Run tests
        run: mage Test
      - name: Cross Compile
        run: mage XBuildAll
      # Publish is a manual step for now that devs build locally and upload to a release
      # - name: Publish
      #   if: ${{ github.event_name == 'push' }}
      #   run: mage Publish